// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    NewContent: typeof import('./src/components/newContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Silder: typeof import('./src/components/silder/index.vue')['default']
    Tips: typeof import('./src/components/silder/tips.vue')['default']
    TipsScan: typeof import('./src/components/tipsScan.vue')['default']
  }
}
